# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

memcached_connect <- function(host = "localhost", port = 11211L) {
    .Call(`_rlibmc_memcached_connect`, host, port)
}

memcached_set_value <- function(conn, key, value, expiration = 0L) {
    .Call(`_rlibmc_memcached_set_value`, conn, key, value, expiration)
}

memcached_get_value <- function(conn, key) {
    .Call(`_rlibmc_memcached_get_value`, conn, key)
}

memcached_delete_key <- function(conn, key) {
    .Call(`_rlibmc_memcached_delete_key`, conn, key)
}

memcached_disconnect <- function(conn) {
    invisible(.Call(`_rlibmc_memcached_disconnect`, conn))
} 